In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score

In [2]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=0)

In [4]:
separated = [[x for x, t in zip(x_train, y_train) if t == c] for c in np.unique(y_train)]
summaries = [(np.mean(i, axis=0), np.std(i, axis=0)) for i in separated]

In [5]:
def predict(summaries, input_vector):
    probabilities = []
    for class_summaries in summaries:
        class_mean, class_std = class_summaries
        probability = np.prod(stats.norm(class_mean, class_std).pdf(input_vector))
        probabilities.append(probability)
    return np.argmax(probabilities)

def naive_bayes_predict(summaries, x_test):
    predictions = []
    for row in x_test:
        output = predict(summaries, row)
        predictions.append(output)
    return np.array(predictions)
predictions = naive_bayes_predict(summaries, x_test)

In [7]:
ac=accuracy_score(y_test,predictions)*100
cm=confusion_matrix(y_test,predictions)
p=precision_score(y_test,predictions,average='macro')*100
r=recall_score(y_test,predictions,average='macro')*100
print("CONFUSION MATRIX : \n",cm)
print("ACCURACY : ",ac)
print("PRECISION : ",p)
print("RECALL : ",r )

CONFUSION MATRIX : 
 [[40  0  0]
 [ 0 39  0]
 [ 0  8 33]]
ACCURACY :  93.33333333333333
PRECISION :  94.32624113475177
RECALL :  93.4959349593496


In [8]:
al = []
al.append(float(input("ENTER SEPAL LENGTH: ")))
al.append(float(input("ENTER SEPAL WIDTH: ")))
al.append(float(input("ENTER PETAL LENGTH: ")))
al.append(float(input("ENTER PETAL WIDTH: ")))
flower_class = predict(summaries, al)
if flower_class == 0:
    print("\nFLOWER IS SETOSA")
elif flower_class == 1:
    print("\nFLOWER IS VERSICOLOR")
else:
    print("\nFLOWER IS VIRGINICA")

ENTER SEPAL LENGTH: 1
ENTER SEPAL WIDTH: 2
ENTER PETAL LENGTH: 3
ENTER PETAL WIDTH: 1

FLOWER IS VIRGINICA
